import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Vaksetu",
    description: "Generated by create next app",
}
import { createClient } from "@/lib/supabase/server"

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    const userProfile = user ? {
        name: user.user_metadata?.full_name || user.user_metadata?.name || "",
        email: user.email || "",
        avatar: user.user_metadata?.avatar_url || "",
    } : null;

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
            <AppSidebar user={userProfile} />
            <SidebarInset>{children}</SidebarInset>
        </SidebarProvider>
        </body>
        </html>
    )
}
